vpc_cidr_block       = "10.0.0.0/16"
subnet_cidr_block    = "10.0.10.0/24"
avail_zone           = "us-east-1a"
env_prefix           = "dev"
my_ip                = "119.160.64.150/32"
instance_type        = "t2.micro"
public_key_location  = "/Users/bilal/.ssh/id_rsa.pub"
private_key_location = "/Users/bilal/.ssh/id_rsa"